### ISSUE TITLE
Implementation problems under Docker construction

### ISSUE THREAD

**Issue by Nelocompne** [charlotte-xiao/NCM2MP3-By-JAVA#11]
我是在linux环境的docker下完成的：
构建的`Dockerfile`
```Dockerfile
FROM openjdk:8
COPY . /usr/src/myapp
WORKDIR /usr/src/myapp
ENTRYPOINT ["java", "-jar", "NCM2MP3.jar"]
```

`~/music`中以及`/music`中包含`.ncm`文件
执行错误：

```shell
-> % sudo docker run --rm minn/ncm2mp3:v0.1 -h
Usage: java -jar NCM2MP3.jar [command]
If don't add command, there will open NCM2MP3 GUI directly
[Command List]
-v,-view                      : open NCM View GUI(default command)
-c,--convert [path] ...       : convert NCM File in path to ./output directory
-h,-help                      : Help about any command
```
```shell
-> % sudo docker run --rm -v ~/music:/music minn/ncm2mp3:v0.1 -c /music
Output dir is set to: /usr/src/myapp/.:output
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1927)
        at utils.Utils.listAllFiles(Utils.java:56)
        at service.command.ConvertCommand.lambda$handle$0(ConvertCommand.java:24)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at service.command.ConvertCommand.handle(ConvertCommand.java:24)
        at service.Interpreter.handleArgs(Interpreter.java:38)
        at main.main(main.java:9)
```

由于我并不了解开发、代码、以及编程。以上附上了我所有可参考的信息。
但个人判断可能为该处关于输出目录的问题：
https://github.com/charlotte-xiao/NCM2MP3/blob/38835c0cfad317dcddee6a6f8436e25e01830321/src/main/java/service/command/ConvertCommand.java#L20

整体预览：
![图片](https://user-images.githubusercontent.com/40271506/226089886-aaeb91c9-a16c-44eb-b0d9-6de814cf450c.png)

感谢您的工作，以上。

**Comment by Nelocompne** [comment]
追加执行方式（只是参考，实际上和上面并没有太大区别）：
```shell
-> % sudo docker run --rm -v ~/music:/music minn/ncm2mp3:v0.1 -c /music
Output dir is set to: /usr/src/myapp/.:output
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1927)
        at utils.Utils.listAllFiles(Utils.java:56)
        at service.command.ConvertCommand.lambda$handle$0(ConvertCommand.java:24)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at service.command.ConvertCommand.handle(ConvertCommand.java:24)
        at service.Interpreter.handleArgs(Interpreter.java:38)
        at main.main(main.java:9)
```

**Comment by charlotte-xiao** [comment]
Thanks for your issue commit~
I read some information about File API. I make a mistake in using a separator of the filename.
```
    /**
     * The system-dependent default name-separator character.  This field is
     * initialized to contain the first character of the value of the system
     * property <code>file.separator</code>.  On UNIX systems the value of this
     * field is <code>'/'</code>; on Microsoft Windows systems it is <code>'\\'</code>.
     *
     * @see     java.lang.System#getProperty(java.lang.String)
     */
    public static final char separatorChar = fs.getSeparator();

    /**
     * The system-dependent default name-separator character, represented as a
     * string for convenience.  This string contains a single character, namely
     * {@link #separatorChar}.
     */
    public static final String separator = "" + separatorChar;

    /**
     * The system-dependent path-separator character.  This field is
     * initialized to contain the first character of the value of the system
     * property <code>path.separator</code>.  This character is used to
     * separate filenames in a sequence of files given as a <em>path list</em>.
     * On UNIX systems, this character is <code>':'</code>; on Microsoft Windows systems it
     * is <code>';'</code>.
     *
     * @see     java.lang.System#getProperty(java.lang.String)
     */
    public static final char pathSeparatorChar = fs.getPathSeparator();

```

I will use `File.separator` instead of `File. pathSeparatorChar `. Thanks and regards~

**Comment by Nelocompne** [comment]
很抱歉，虽然输出目录确实得到了改变，但依然没有解决问题。
仅仅只是：
```shell
Output dir is set to: /usr/src/myapp/.:output
                                      ↓  // change
Output dir is set to: /usr/src/myapp/./output
```

完整：
```shell
-> % sudo docker run --rm -v ~/music:/music minn/ncm2mp3:v0.2 -c /music
Output dir is set to: /usr/src/myapp/./output
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1927)
        at utils.Utils.listAllFiles(Utils.java:56)
        at service.command.ConvertCommand.lambda$handle$0(ConvertCommand.java:24)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at service.command.ConvertCommand.handle(ConvertCommand.java:24)
        at service.Interpreter.handleArgs(Interpreter.java:38)
        at main.main(main.java:9)
```

**Comment by charlotte-xiao** [comment]
it seems your files include some file name is shorter than 3 chars, and I will add some check for it.
```java
public static void listAllFiles(ArrayList<File> arrayList, File file) {
        if (!file.isDirectory()) {
            String name = file.getName().trim();
            if ("ncm".equalsIgnoreCase(name.substring(name.length() - 3))) {
                arrayList.add(file);
            }
        } else {
            File[] files = file.listFiles();
            assert files != null;
            for (File f : files) {
                listAllFiles(arrayList, f);
            }
        }
    }
```

**Comment by Nelocompne** [comment]
最新的pull对问题还没有新的进展。
您可以继续项目工作，有新的进展我会尽快回复。如果该问题在未来解决，我将会关闭此反馈。
感谢。

**Comment by Nelocompne** [comment]
> 最新的pull对问题还没有新的进展。
您可以继续项目工作，有新的进展我会尽快回复。如果该问题在未来解决，我将会关闭此反馈。
感谢。

补充一点，我的ncm文件名中包含例如这样（对内容进行了版权规避）：
```shell
% ls .
'ア (Remix) - name＊2,d.ncm'
```

我尝试改变文件名例如：
```
123name.ncm
```

但是依然会出现问题。以上

**Comment by Nelocompne** [comment]
> > 最新的pull对问题还没有新的进展。
> > 您可以继续项目工作，有新的进展我会尽快回复。如果该问题在未来解决，我将会关闭此反馈。
> > 感谢。
> 
> 补充一点，我的ncm文件名中包含例如这样（对内容进行了版权规避）：
> 
> ```shell
> % ls .
> 'ア (Remix) - name＊2,d.ncm'
> ```
> 
> 我尝试改变文件名例如：
> 
> ```
> 123name.ncm
> ```
> 
> 但是依然会出现问题。以上

最新情况，
`~/test/11111111111111111.ncm`
`~/test/22222222222222222.ncm`
`~/test/33333333333333333.ncm`

```shell
-> % sudo docker run --rm -v ~/test:/music minn/ncm2mp3:v0.3 -c /music
Output dir is set to: /usr/src/myapp/./output
java.io.FileNotFoundException: /usr/src/myapp/./output/33333333333333333.flac (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at service.Converter.ncm2Mp3(Converter.java:52)
        at service.command.ConvertCommand.lambda$null$1(ConvertCommand.java:26)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
java.io.FileNotFoundException: /usr/src/myapp/./output/11111111111111111.flac (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at service.Converter.ncm2Mp3(Converter.java:52)
        at service.command.ConvertCommand.lambda$null$1(ConvertCommand.java:26)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
java.io.FileNotFoundException: /usr/src/myapp/./output/22222222222222222.flac (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
转换失败文件：/usr/src/myapp/./output/33333333333333333.flac
转换失败文件：/usr/src/myapp/./output/11111111111111111.flac
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at service.Converter.ncm2Mp3(Converter.java:52)
        at service.command.ConvertCommand.lambda$null$1(ConvertCommand.java:26)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
转换失败文件：/usr/src/myapp/./output/22222222222222222.flac
^C%                                                                                                                                                                                                      

...
```
