### ISSUE TITLE
Convert Failed, index out of bound

### ISSUE THREAD

**Issue by Xrondev** [charlotte-xiao/NCM2MP3-By-JAVA#23]
my NCM music file was retrieved on July 4, 2023. Both running from source code and running with jar file were tried, and both reported the following problem. 10 files were attempted and all failed with similar errors. 
The environment was correctly set, those errors **happened when converting the music.**

``` shell
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 26519 out of bounds for length 256
	at com.alibaba.fastjson.util.IOUtils.decodeBase64(IOUtils.java:467)
	at com.alibaba.fastjson.parser.JSONScanner.bytesValue(JSONScanner.java:132)
	at com.alibaba.fastjson.serializer.ObjectArrayCodec.deserialze(ObjectArrayCodec.java:137)
	at com.alibaba.fastjson.parser.deserializer.DefaultFieldDeserializer.parseField(DefaultFieldDeserializer.java:88)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseField(JavaBeanDeserializer.java:1278)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:893)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.parseRest(JavaBeanDeserializer.java:1624)
	at com.alibaba.fastjson.parser.deserializer.FastjsonASMDeserializer_7_Mata.deserialze(Unknown Source)
	at com.alibaba.fastjson.parser.deserializer.JavaBeanDeserializer.deserialze(JavaBeanDeserializer.java:287)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:705)
	... 10 more
```
I have searched through the issues and got no solution for this (the ArrayIndexOutOfBoundsException). Looks like they have some new tricks?

**Comment by charlotte-xiao** [comment]
Sorry, I'm not sure if it was caused by the NetEase Cloud NCM format modification.
#22
